[input]
url_prefix = "https://prendergastc.github.io/profile"
html_selector = "main"
base_directory = "output"

[[input.files]]
path = "pages/search.html"
url = "/pages/search.html"
title = "Search"

[[input.files]]
path = "db_and_programming.html"
url = "/db_and_programming.html"
title = "Database, Programming, and Software Skills"

[[input.files]]
path = "esri_certificates.html"
url = "/esri_certificates.html"
title = "ESRI Certificates"

[[input.files]]
path = "gis_qualifications.html"
url = "/gis_qualifications.html"
title = "GIS Qualifications"

[[input.files]]
path = "transcripts.html"
url = "/transcripts.html"
title = "Academic Transcripts"

[[input.files]]
path = "urban_green_spaces.html"
url = "/urban_green_spaces.html"
title = "Urban Green Spaces in San Francisco and San Jose, California"

[[input.files]]
path = "wildfire_dashboard.html"
url = "/wildfire_dashboard.html"
title = "Wildfire Dashboard"

[[input.files]]
path = "kenya_elephants.html"
url = "/kenya_elephants.html"
title = "Analysis of Suitable Elephant Habitat, Narok and Kajiado Districts, Kenya"

[[input.files]]
path = "santa_cruz_public_works.html"
url = "/santa_cruz_public_works.html"
title = "Public Works Department Assets, City of Santa Cruz"

[[input.files]]
path = "santa_cruz_precincts.html"
url = "/santa_cruz_precincts.html"
title = "Voting Precincts, Santa Cruz County"

[[input.files]]
path = "local_park_amenities.html"
url = "/local_park_amenities.html"
title = "Local Park Amenities in the Cambrian Park neighborhood"

[[input.files]]
path = "santa_cruz_sanitation.html"
url = "/santa_cruz_sanitation.html"
title = "Sanitation Drawing Index Map, Santa Cruz County"

[[input.files]]
path = "marin_smoke_detector.html"
url = "/marin_smoke_detector.html"
title = "Marin Smoke Detectors"

[[input.files]]
path = "portland_economic_vulnerability.html"
url = "/portland_economic_vulnerability.html"
title = "Portland Economic Vulnerability"

[[input.files]]
path = "puget_sound_traffic_violations.html"
url = "/puget_sound_traffic_violations.html"
title = "Puget Sound Traffic Violations"

[[input.files]]
path = "mountain_lion_modelbuilder.html"
url = "/mountain_lion_modelbuilder.html"
title = "Mountain Lion Corridors, Los Angeles, CA"

[[input.files]]
path = "tree_cover_and_heat.html"
url = "/tree_cover_and_heat.html"
title = "The Impact of Tree Cover on the Urban Heat Island Effect"

[[input.files]]
path = "north_dakota_housing.html"
url = "/north_dakota_housing.html"
title = "The impact of the housing shortage on oil workers"

[[input.files]]
path = "calero_geodatabase_design.html"
url = "/calero_geodatabase_design.html"
title = "Geodatabase Design, Calero County Park, Santa Clara County, California"

[[input.files]]
path = "analysis_3d.html"
url = "/analysis_3d.html"
title = "ArcGIS Pro: An Overview of 3D Analysis"

[[input.files]]
path = "deep_learning.html"
url = "/deep_learning.html"
title = "ArcGIS: Introduction to Deep Learning"

[[input.files]]
path = "geodatabase_design.html"
url = "/geodatabase_design.html"
title = "Geodatabase Design Project"

[[input.files]]
path = "autocad.html"
url = "/autocad.html"
title = "Working with AutoCAD data"

[[input.files]]
path = "understanding_metadata.html"
url = "/understanding_metadata.html"
title = "Understanding Metadata"

[[input.files]]
path = "utility_networks.html"
url = "/utility_networks.html"
title = "ArcGIS Network Management: Utility Network Overview"

[[input.files]]
path = "data_storage.html"
url = "/data_storage.html"
title = "Data Storage Strategies"

[[input.files]]
path = "san_jose_from_space.html"
url = "/san_jose_from_space.html"
title = "San Jose from Space"

[[input.files]]
path = "mrosd.html"
url = "/mrosd.html"
title = "Midpeninsula Regional Open Space District Map Series"

[[input.files]]
path = "portland_schools.html"
url = "/portland_schools.html"
title = "Portland Schools"

[[input.files]]
path = "california_ecology.html"
url = "/california_ecology.html"
title = "California Ecology Field Trip Observations"

[[input.files]]
path = "urban_heat_islands.html"
url = "/urban_heat_islands.html"
title = "Analysis of the Urban Heat Island Effect, Santa Clara County"

[[input.files]]
path = "california_ozone.html"
url = "/california_ozone.html"
title = "California Ozone"

[[input.files]]
path = "california_proposition_37.html"
url = "/california_proposition_37.html"
title = "Support for California Proposition 37"

[[input.files]]
path = "santa_clara_valley_open_space.html"
url = "/santa_clara_valley_open_space.html"
title = "Santa Clara Valley Open Space Story Maps"

[[input.files]]
path = "splihaus.html"
url = "/splihaus.html"
title = "Spilhaus World Oceans Map"

[[input.files]]
path = "massachucetts_parks.html"
url = "/massachucetts_parks.html"
title = "Massachucetts Parks"

[[input.files]]
path = "landuse_app.html"
url = "/landuse_app.html"
title = "Landuse change in Samut Songkhram, Thailand"

[[input.files]]
path = "san_bernadino_modelbuilder.html"
url = "/san_bernadino_modelbuilder.html"
title = "Location Analysis for New Carbonate Mine, San Bernadino National Forest"

[[input.files]]
path = "lyell_glacier.html"
url = "/lyell_glacier.html"
title = "Lyell Glacier, Yosemite National Park"

[[input.files]]
path = "ai_implications_for_spatial_science.html"
url = "/ai_implications_for_spatial_science.html"
title = "The Emergence of AI Engineering and its Implications for Spatial Science"

[[input.files]]
path = "arcgis_and_jupyter_for_spatial_data_science.html"
url = "/arcgis_and_jupyter_for_spatial_data_science.html"
title = "Explore How to Use ArcGIS and Jupyter for Geospatial Data Science"

[[input.files]]
path = "data_management_for_gis_projects.html"
url = "/data_management_for_gis_projects.html"
title = "Data Management for GIS Projects"

[[input.files]]
path = "geo_ai_for_transportation.html"
url = "/geo_ai_for_transportation.html"
title = "GeoAI for Transportation Webinar"

[[input.files]]
path = "integrating_deep_learning_with_arcgis_using_python.html"
url = "/integrating_deep_learning_with_arcgis_using_python.html"
title = "Integrating Deep Learning with ArcGIS using Python"

[[input.files]]
path = "machine_learning_ai_and_arcgis.html"
url = "/machine_learning_ai_and_arcgis.html"
title = "Machine Learning, Artificial Intelligence and ArcGIS"

[[input.files]]
path = "planning_you_gis_career.html"
url = "/planning_you_gis_career.html"
title = "Planning your GIS Career discussion with Nathan Heazlewood and Joseph Kerski"

[[input.files]]
path = "predict_urban_growth_patterns_using_machine_learning.html"
url = "/predict_urban_growth_patterns_using_machine_learning.html"
title = "Predict Urban Growth Patterns Using Machine Learning with ArcGIS Pro and R"

[[input.files]]
path = "spatial_analysis_and_data_science.html"
url = "/spatial_analysis_and_data_science.html"
title = "Spatial Analysis and Data Science"

[[input.files]]
path = "spatial_data_science_transforming_our_planet.html"
url = "/spatial_data_science_transforming_our_planet.html"
title = "Spatial Data Science: Transforming Our Planet"

[[input.files]]
path = "underutilization_of_gis_and_how_to_cure_it.html"
url = "/underutilization_of_gis_and_how_to_cure_it.html"
title = "Underutilization of GIS and How to Cure it"

[[input.files]]
path = "machine_learning_in_arcgis.html"
url = "/machine_learning_in_arcgis.html"
title = "Machine Learning in ArcGIS"

[[input.files]]
path = "farmers_market_site_selection.html"
url = "/farmers_market_site_selection.html"
title = "Farmers Market Site Selection"

[[input.files]]
path = "homeless_app.html"
url = "/homeless_app.html"
title = "Homelessness in Santa Clara County"

[[input.files]]
path = "red_rock_app.html"
url = "/red_rock_app.html"
title = "Red Rock Canyon Hiking Trails"

[[input.files]]
path = "target_market_analysis.html"
url = "/target_market_analysis.html"
title = "Target Market Analysis"

[[input.files]]
path = "hawaii_app.html"
url = "/hawaii_app.html"
title = "Volcanic hazards, Island of Hawaii"

[output]
debug = true
