# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-09-10 15:38:55
"""
import arcpy

def SelectAreas():  # Select Areas fro Elephant Habitat Study

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    LanduseCut = "C:\\arcgis_projects\\ucd\\adv_gis\\ModelBuilder\\NK_Model.gdb\\LanduseCut"
    Expression = "Land_use IN ('bushland (dense)', 'bushland (sparse)', 'forest', 'grassland', 'woodland')"
    MarketTowns = "C:\\arcgis_projects\\ucd\\adv_gis\\ModelBuilder\\NK_Model.gdb\\MarketTowns"
    Distance_meters_1 = 2500
    Major_Towns = "C:\\arcgis_projects\\ucd\\adv_gis\\ModelBuilder\\NK_Model.gdb\\Major_Towns"
    Distance_meters_2 = 2500
    Roads = "C:\\arcgis_projects\\ucd\\adv_gis\\ModelBuilder\\NK_Model.gdb\\Roads"
    Distance_meters_3 = 2500
    AGBuff10K = "C:\\arcgis_projects\\ucd\\adv_gis\\ModelBuilder\\NK_Model.gdb\\AGBuff10K"

    # Process: Make Feature Layer (Make Feature Layer) (management)
    Preferred_Landuse = "Preferred_Landuse"
    arcpy.management.MakeFeatureLayer(in_features=LanduseCut, out_layer=Preferred_Landuse, where_clause=Expression)

    # Process: Buffer (Buffer) (analysis)
    MrkTownBuff = "C:\\arcgis_projects\\ucd\\adv_gis\\ModelBuilder\\NK_Model.gdb\\MrkTownBuff"
    arcpy.analysis.Buffer(in_features=MarketTowns, out_feature_class=MrkTownBuff, buffer_distance_or_field=Distance_meters_1, dissolve_option="ALL")

    # Process: Buffer (2) (Buffer) (analysis)
    MjrTownBuff = "C:\\arcgis_projects\\ucd\\adv_gis\\ModelBuilder\\NK_Model.gdb\\MjrTownBuff"
    arcpy.analysis.Buffer(in_features=Major_Towns, out_feature_class=MjrTownBuff, buffer_distance_or_field=Distance_meters_2, dissolve_option="ALL")

    # Process: Buffer (3) (Buffer) (analysis)
    Roads_Buffer = "C:\\arcgis_projects\\ucd\\adv_gis\\ModelBuilder\\NK_Model.gdb\\Roads_Buffer"
    arcpy.analysis.Buffer(in_features=Roads, out_feature_class=Roads_Buffer, buffer_distance_or_field=Distance_meters_3, dissolve_option="ALL")

    # Process: Merge (Merge) (management)
    AllBUff = "C:\\arcgis_projects\\ucd\\adv_gis\\ModelBuilder\\NK_Model.gdb\\AllBUff"
    arcpy.management.Merge(inputs=[MrkTownBuff, MjrTownBuff, Roads_Buffer, AGBuff10K], output=AllBUff)

    # Process: Union (Union) (analysis)
    AllBUff_Union = "C:\\arcgis_projects\\ucd\\adv_gis\\ModelBuilder\\NK_Model.gdb\\AllBUff_Union"
    arcpy.analysis.Union(in_features=[[Preferred_Landuse, ""], [AllBUff, ""]], out_feature_class=AllBUff_Union)

    # Process: Make Feature Layer (2) (Make Feature Layer) (management)
    TempResults = "TempResults"
    arcpy.management.MakeFeatureLayer(in_features=AllBUff_Union, out_layer=TempResults, where_clause="FID_AllBUff = -1")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\arcgis_projects\\ucd\\adv_gis\\ModelBuilder\\NK_Model.gdb", workspace="C:\\arcgis_projects\\ucd\\adv_gis\\ModelBuilder\\NK_Model.gdb"):
        SelectAreas()
